// Database types for Supabase tables

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          username: string;
          full_name: string | null;
          avatar_url: string | null;
          email: string | null;
          experience_level: string;
          current_position: string | null;
          years_of_experience: number;
          programming_languages: string[];
          learning_style: string | null;
          daily_goal_minutes: number;
          timezone: string;
          total_xp: number;
          current_streak: number;
          longest_streak: number;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string;
          last_login: string | null;
          is_active: boolean;
        };
        Insert: {
          id: string;
          username: string;
          full_name?: string | null;
          avatar_url?: string | null;
          email?: string | null;
          experience_level?: string;
          current_position?: string | null;
          years_of_experience?: number;
          programming_languages?: string[];
          learning_style?: string | null;
          daily_goal_minutes?: number;
          timezone?: string;
          total_xp?: number;
          current_streak?: number;
          longest_streak?: number;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          username?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          email?: string | null;
          experience_level?: string;
          current_position?: string | null;
          years_of_experience?: number;
          programming_languages?: string[];
          learning_style?: string | null;
          daily_goal_minutes?: number;
          timezone?: string;
          total_xp?: number;
          current_streak?: number;
          longest_streak?: number;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
          is_active?: boolean;
        };
      };
      roadmaps: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description: string | null;
          long_description: string | null;
          difficulty_level: string;
          category: string | null;
          subcategory: string | null;
          estimated_weeks: number | null;
          estimated_hours: number | null;
          prerequisites: string[];
          learning_objectives: string[];
          career_outcomes: string[];
          total_modules: number;
          total_topics: number;
          is_published: boolean;
          is_featured: boolean;
          created_by: string | null;
          meta_title: string | null;
          meta_description: string | null;
          cover_image: string | null;
          total_enrollments: number;
          average_completion_rate: number;
          average_rating: number;
          created_at: string;
          updated_at: string;
        };
      };
      modules: {
        Row: {
          id: string;
          roadmap_id: string;
          title: string;
          description: string | null;
          learning_objectives: string[];
          order_index: number;
          estimated_hours: number | null;
          prerequisites: string[];
          required_skills: string[];
          module_type: string;
          created_at: string;
        };
      };
      topics: {
        Row: {
          id: string;
          module_id: string;
          roadmap_id: string;
          title: string;
          description: string | null;
          order_index: number;
          topic_type: string | null;
          difficulty_level: string | null;
          estimated_minutes: number | null;
          has_prerequisites: boolean;
          prerequisite_topics: string[];
          has_lab: boolean;
          has_quiz: boolean;
          has_submission: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          module_id: string;
          roadmap_id: string;
          title: string;
          description?: string | null;
          order_index: number;
          topic_type?: string | null;
          difficulty_level?: string | null;
          estimated_minutes?: number | null;
          has_prerequisites?: boolean;
          prerequisite_topics?: string[];
          has_lab?: boolean;
          has_quiz?: boolean;
          has_submission?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          module_id?: string;
          roadmap_id?: string;
          title?: string;
          description?: string | null;
          order_index?: number;
          topic_type?: string | null;
          difficulty_level?: string | null;
          estimated_minutes?: number | null;
          has_prerequisites?: boolean;
          prerequisite_topics?: string[];
          has_lab?: boolean;
          has_quiz?: boolean;
          has_submission?: boolean;
          created_at?: string;
        };
      };
      user_roadmaps: {
        Row: {
          id: string;
          user_id: string;
          roadmap_id: string;
          status: string;
          enrollment_date: string;
          enrolled_at: string;
          started_at: string | null;
          completed_at: string | null;
          paused_at: string | null;
          current_module_id: string | null;
          current_topic_id: string | null;
          progress_percentage: number;
          total_topics: number;
          completed_topics: number;
          total_time_minutes: number;
          target_completion_date: string | null;
          daily_time_goal: number;
          last_accessed: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          roadmap_id: string;
          status?: string;
          enrollment_date?: string;
          enrolled_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          paused_at?: string | null;
          current_module_id?: string | null;
          current_topic_id?: string | null;
          progress_percentage?: number;
          total_topics?: number;
          completed_topics?: number;
          total_time_minutes?: number;
          target_completion_date?: string | null;
          daily_time_goal?: number;
          last_accessed?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          roadmap_id?: string;
          status?: string;
          enrollment_date?: string;
          enrolled_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          paused_at?: string | null;
          current_module_id?: string | null;
          current_topic_id?: string | null;
          progress_percentage?: number;
          total_topics?: number;
          completed_topics?: number;
          total_time_minutes?: number;
          target_completion_date?: string | null;
          daily_time_goal?: number;
          last_accessed?: string | null;
        };
      };
      user_progress: {
        Row: {
          id: string;
          user_id: string;
          topic_id: string;
          status: string;
          is_completed: boolean;
          started_at: string | null;
          completed_at: string | null;
          completion_date: string | null;
          last_accessed: string;
          time_spent_minutes: number;
          estimated_time_minutes: number | null;
          attempts: number;
          score: number | null;
          max_score: number | null;
          personal_notes: string | null;
          bookmarked: boolean;
          difficulty_rating: number | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          topic_id: string;
          status?: string;
          is_completed?: boolean;
          started_at?: string | null;
          completed_at?: string | null;
          completion_date?: string | null;
          last_accessed?: string;
          time_spent_minutes?: number;
          estimated_time_minutes?: number | null;
          attempts?: number;
          score?: number | null;
          max_score?: number | null;
          personal_notes?: string | null;
          bookmarked?: boolean;
          difficulty_rating?: number | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          topic_id?: string;
          status?: string;
          is_completed?: boolean;
          started_at?: string | null;
          completed_at?: string | null;
          completion_date?: string | null;
          last_accessed?: string;
          time_spent_minutes?: number;
          estimated_time_minutes?: number | null;
          attempts?: number;
          score?: number | null;
          max_score?: number | null;
          personal_notes?: string | null;
          bookmarked?: boolean;
          difficulty_rating?: number | null;
        };
      };
      user_achievements: {
        Row: {
          id: string;
          user_id: string;
          achievement_type: string;
          achievement_name: string;
          description: string | null;
          achieved_at: string;
          metadata: Json;
          xp_awarded: number;
          badge_icon: string | null;
          badge_color: string | null;
          is_visible: boolean;
          is_featured: boolean;
        };
      };
      learning_content: {
        Row: {
          id: string;
          topic_id: string;
          content_type: string;
          content: string;
          order_index: number;
          duration_minutes: number | null;
          is_interactive: boolean;
          file_attachments: string[];
          external_links: Json;
          quiz_data: Json | null;
          lab_instructions: string | null;
          solution_code: string | null;
          hints: string[];
          difficulty_rating: number | null;
          last_updated: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          topic_id: string;
          content_type: string;
          content: string;
          order_index: number;
          duration_minutes?: number | null;
          is_interactive?: boolean;
          file_attachments?: string[];
          external_links?: Json;
          quiz_data?: Json | null;
          lab_instructions?: string | null;
          solution_code?: string | null;
          hints?: string[];
          difficulty_rating?: number | null;
          last_updated?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          topic_id?: string;
          content_type?: string;
          content?: string;
          order_index?: number;
          duration_minutes?: number | null;
          is_interactive?: boolean;
          file_attachments?: string[];
          external_links?: Json;
          quiz_data?: Json | null;
          lab_instructions?: string | null;
          solution_code?: string | null;
          hints?: string[];
          difficulty_rating?: number | null;
          last_updated?: string;
          created_at?: string;
        };
      };
    };
  };
}
